baseURL: "https://indiefeed.link/"
languageCode: "en-us"
title: "IndieFeed"
enableRobotsTXT: true
disableAliases: true

imaging:
  quality: 100

outputs:
  home: ["HTML", "REDIRECTS", "HEADERS"]
  section: ["HTML"]
  taxonomy: ["HTML"]
  term: ["HTML"]

outputFormats:
  REDIRECTS:
    mediaType: "text/netlify"
    baseName: "_redirects"
    isPlainText: true
    notAlternative: true
  HEADERS:
    mediaType: "text/netlify"
    baseName: "_headers"
    isPlainText: true
    notAlternative: true

mediaTypes:
  text/netlify:
    suffixes: []
  application/atom+xml:
    suffixes: ["xml"]
